require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false
Layout/AlignHash:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/helpers/chart_helper.rb'

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'spec/models/user_spec.rb'
    - 'spec/models/currency_log_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/NestedGroups:
  Enabled: false

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/pages_controller_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/controllers/pages_controller_spec.rb'
