require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/helpers/chart_helper.rb'
