require: rubocop-rspec
inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5
