default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: poe-currency-log_development

test:
  <<: *default
  database: poe-currency-log_test

production:
  <<: *default
  database: poe-currency-log_production
  username: poe-currency-log
  password: <%= ENV['POE-CURRENCY-LOG_DATABASE_PASSWORD'] %>
