default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: poe-currency-log_development

test:
  <<: *default
  database: poe-currency-log_test

production:
  <<: *default
  database: poe-currency-log_production
